[package]
name = "action-individual-commits-check"
description = "Allow to check individual commits of a push or pull request"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
