name: Test consuming this action
on:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]
  workflow_dispatch:
jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./@dev
        with:
          check-cmd: "cargo fmt --check"

  test_missing_env_var:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test_missing_envvar
        continue-on-error: true
        uses: ./@dev
        with:
          check-cmd: "cargo fmt --check"
      - name: Verify failure
        if: steps.test_missing_envvar.outputs.error != ''
        run: echo "Failed as expected"
      - name: Unexpected success
        if: steps.test_missing_envvar.outputs.error == ''
        run: echo "Succeeded unexpectedly" && exit 1


  test_missing_check-cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test_missing_check-cmd
        continue-on-error: true
        uses: ./@dev
        env:
          GITHUB_EVENT: ${{ github.event }}
          GITHUB_EVENT_JSON: ${{ toJson(github.event) }}
      - name: Verify failure
        if: steps.test_missing_check-cmd.outputs.error != ''
        run: echo "Failed as expected"
      - name: Unexpected success
        if: steps.test_missing_check-cmd.outputs.error == ''
        run: echo "Succeeded unexpectedly" && exit 1
